#!/usr/bin/env bash

# cleanup.sh - Clean up temporary files
# Usage: ./cleanup.sh <VIDEO_ID> [--keep-state]
# By default this removes the state file as well, so a completed run leaves no
# resumable state behind unless --keep-state is requested for debugging.
# This also removes chunk artifacts generated by transcribe-deepgram and
# chunk-text so the next run starts from a clean temp workspace.

if [ $# -lt 1 ]; then
    echo "Usage: $0 <VIDEO_ID> [--keep-state]"
    exit 1
fi

VIDEO_ID="$1"
KEEP_STATE=false

if [ "${2:-}" = "--keep-state" ]; then
    KEEP_STATE=true
fi

echo "🧹 Cleaning up temporary files for video: $VIDEO_ID"

# Remove all temp files related to this video
rm -f /tmp/${VIDEO_ID}.*
rm -f /tmp/${VIDEO_ID}_*.json
rm -f /tmp/${VIDEO_ID}_chunk_*
rm -f /tmp/${VIDEO_ID}_raw_text.txt
rm -f /tmp/${VIDEO_ID}_structured.txt
rm -f /tmp/${VIDEO_ID}_optimized.txt
rm -f /tmp/${VIDEO_ID}_combined_transcript.txt
rm -rf /tmp/${VIDEO_ID}_chunks/
if [ "$KEEP_STATE" != true ]; then
    rm -f /tmp/${VIDEO_ID}_state.md
fi

echo "✅ Cleanup complete"
