#!/usr/bin/env bash
set -euo pipefail

# cleanup.sh - Clean up temporary files
# Usage: ./cleanup.sh <VIDEO_ID> [--keep-state]
# By default this removes the state file as well, so a completed run leaves no
# resumable state behind unless --keep-state is requested for debugging.
# This also removes chunk artifacts generated by transcribe-deepgram and
# chunk-text so the next run starts from a clean temp workspace.

if [ $# -lt 1 ]; then
    echo "Usage: $0 <VIDEO_ID> [--keep-state]" >&2
    exit 1
fi

VIDEO_ID="$1"
KEEP_STATE=false

if [ -z "$VIDEO_ID" ]; then
    echo "❌ Error: VIDEO_ID must not be empty" >&2
    exit 1
fi

case "$VIDEO_ID" in
    *[!A-Za-z0-9_-]*)
        echo "❌ Error: VIDEO_ID contains unsafe characters: $VIDEO_ID" >&2
        exit 1
        ;;
esac

if [ "${2:-}" = "--keep-state" ]; then
    KEEP_STATE=true
fi

echo "🧹 Cleaning up temporary files for video: $VIDEO_ID"

STATE_FILE="/tmp/${VIDEO_ID}_state.md"
MACHINE_STATE_FILE="/tmp/${VIDEO_ID}_machine_state.json"
KEEP_DIR=""

if [ "$KEEP_STATE" = true ]; then
    KEEP_DIR=$(mktemp -d)
    if [ -f "$STATE_FILE" ]; then
        mv "$STATE_FILE" "$KEEP_DIR/state.md"
    fi
    if [ -f "$MACHINE_STATE_FILE" ]; then
        mv "$MACHINE_STATE_FILE" "$KEEP_DIR/machine_state.json"
    fi
fi

# Remove all temp files related to this video
rm -f /tmp/${VIDEO_ID}.*
rm -f /tmp/${VIDEO_ID}_*.json
rm -f /tmp/${VIDEO_ID}_chunk_*
rm -f /tmp/${VIDEO_ID}_raw_text.txt
rm -f /tmp/${VIDEO_ID}_structured.txt
rm -f /tmp/${VIDEO_ID}_optimized.txt
rm -f /tmp/${VIDEO_ID}_combined_transcript.txt
rm -rf /tmp/${VIDEO_ID}_chunks/
rm -rf /tmp/${VIDEO_ID}_downloads/
if [ "$KEEP_STATE" != true ]; then
    rm -f "$STATE_FILE"
fi

if [ "$KEEP_STATE" = true ]; then
    if [ -f "$KEEP_DIR/state.md" ]; then
        mv "$KEEP_DIR/state.md" "$STATE_FILE"
    fi
    if [ -f "$KEEP_DIR/machine_state.json" ]; then
        mv "$KEEP_DIR/machine_state.json" "$MACHINE_STATE_FILE"
    fi
    rmdir "$KEEP_DIR" 2>/dev/null || true
fi

echo "✅ Cleanup complete"
